name: "GHA - Deploy Instance Watcher"

on: 
  push:
    branches:
    - v0.3.3

jobs:
  aws_sam:
    runs-on: ubuntu-latest
    steps:
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GhA-Instance-Watcher

      - name: Git Checkout
        uses: actions/checkout@master

      - name: Test IAM credentials - whoami?
        run: |
          aws sts get-caller-identity

      - name: Python Requirements
        run: |
          sudo apt-get install python3-setuptools python3-dev python3-wheel -y
          pip3 install --upgrade pip
          pip3 install wheel

      - name: Package Lambda
        run: |
          make package \
            Project=zoph

      - name: Package Lambda Layer
        run: |
          make layer

      - name: Deploy
        run: |
          make deploy \
              EnableSlack=1 \
              SlackWebHook=${{ secrets.SLACK_HOOK }} \
              Recipients=${{ secrets.RECIPIENTS }} \
              Sender=${{ secrets.SENDER }} \
              Project=zoph